version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:0-17
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:mailhog

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025